name: Build Zappy

on:
    push:
        branches:
            - '*'
    pull_request:
        types:
          - opened
          - synchronize
          - edited
          - reopened

env:
    BUILD_TYPE: Release
    AI_DIR: zappy_ai
    GUI_DIR: zappy_gui
    SERVER_DIR: zappy_server

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Build
              run: |
                  sudo apt-get install libsfml-dev
                  make
