name: Build Zappy

on:
    push:
        branches:
            - '*'
    pull_request:
        types:
          - opened
          - synchronize
          - edited
          - reopened

env:
    BUILD_TYPE: Release
    AI_DIR: zappy_ai
    GUI_DIR: zappy_gui
    SERVER_DIR: zappy_server
    MIRROR_URL: git@github.com:EpitechPromo2026/B-YEP-400-REN-4-1-zappy-thomas.juin.git

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Build Zappy_AI
              run: |
                  cd $AI_DIR
                  ./build.sh

            - name: Install CMake
              run: sudo apt-get update && sudo apt-get install -y cmake

            - name: Build Zappy_GUI
              run: cmake -S $GUI_DIR -B $GUI_DIR/build -DCMAKE_BUILD_TYPE=$BUILD_TYPE && cmake --build $GUI_DIR/build

            - name: Build Zappy_Server
              run: make -C $SERVER_DIR

    push_to_mirror:
      runs-on: ubuntu-latest
      needs: [build]
      name: push-to-mirror
      if: ${{ github.event_name == 'push' }}
      steps:                                              # <-- must use actions/checkout before mirroring!
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: pixta-dev/repository-mirroring-action@v1
          with:
            target_repo_url:
              ${{ env.MIRROR_URL }}
            ssh_private_key:                              # <-- use 'secrets' to pass credential information.
              ${{ secrets.GIT_SSH_PRIVATE_KEY }}